// GENERATED by scripts/generate-previews.mjs — do not edit.
// Regenerated on every `pnpm dev` and `pnpm build`.
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

export const previews: Record<string, ComponentType> = {
	"collapsable-menu": dynamic(() => import("./collapsable-menu/Preview")),
	"dynamic-island": dynamic(() => import("./dynamic-island/Preview")),
	"loading-wipe": dynamic(() => import("./loading-wipe/Preview")),
	"profile-menu": dynamic(() => import("./profile-menu/Preview")),
	"social-bar": dynamic(() => import("./social-bar/Preview")),
	"transaction-status-button": dynamic(() => import("./transaction-status-button/Preview")),
	"vertical-icon-switch": dynamic(() => import("./vertical-icon-switch/Preview")),
};
